### PR TITLE
PERF-5507 Fix AggregateExpressions.yml query definition and data generation

### PR DESCRIPTION
**Pull request by ktbooker**
**Jira Ticket:** [PERF-5507](https://jira.mongodb.org/browse/PERF-5507)

### Whats Changed

Fixed generation of array data to populate arrays of size 10, previously was only making arrays of size 1. 

Additionally fixed a query using an undefined field.

### CODE REVIEW

**Review by parker-felix — COMMENTED** [review]
Per offline discussion, we are going to modify data generation so that each document has the same arrays, to match the original design of the workload.

**Review by parker-felix — APPROVED** [review]
LGTM

**Comment by parker-felix** [comment]
Verified that updated data generation looks good offline so still LGTM.

**Review by leozzx — APPROVED** [review]
lgtm

**Review by miguelangelnieto — APPROVED** [review]

**Pull request merged**
