### PR TITLE
DEVPROD-2192 Add initial CODEOWNERS file, update PR template

### PR DESCRIPTION
**Pull request by thessem**
**Jira Ticket:** [DEVPROD-2192](https://jira.mongodb.org/browse/DEVPROD-2192)

### Whats Changed

- Added a newer version of the CODEOWNERS file that hopefully maps to teams that exist.
- Updated the PR template

### Current Repo Settings
Figured terraform was the best way of displaying this, ignore the "will be imported"/"updated" stuff, I am not proposing any settings changes in this PR.

```
 # module.github.module.genny.github_branch.main will be imported
    resource "github_branch" "main" {
        branch        = "master"
        etag          = "W/\"aab1abea53fedd5213d8473da2809741ad30ef8a07bc97378b8ac44e489693dc\""
        id            = "genny:master"
        ref           = "refs/heads/master"
        repository    = "genny"
        sha           = "b6360b717ee7da1c2d8f76d032011ba2b8a7f33d"
        source_branch = "main"
    }

  # module.github.module.genny.github_branch_default.this will be imported
    resource "github_branch_default" "this" {
        branch     = "master"
        etag       = "W/\"1561743c78a99f870325f27e254ebca3701f6af56bc9df1ae604fb59e8693de4\""
        id         = "genny"
        repository = "genny"
    }

  # module.github.module.genny.github_branch_protection.main will be updated in-place
  # (imported from "genny:master")
    resource "github_branch_protection" "main" {
        allows_deletions                = false
        allows_force_pushes             = false
        enforce_admins                  = false
        force_push_bypassers            = []
        id                              = "MDIwOkJyYW5jaFByb3RlY3Rpb25SdWxlMzY3MTM5Nw=="
        lock_branch                     = false
        pattern                         = "master"
        repository_id                   = "MDEwOlJlcG9zaXRvcnkxMjEyOTEwNDg="
        require_conversation_resolution = false
        require_signed_commits          = false
        required_linear_history         = false

        required_pull_request_reviews {
            dismiss_stale_reviews           = false
            dismissal_restrictions          = []
            pull_request_bypassers          = []
            require_code_owner_reviews      = true
            require_last_push_approval      = false
            required_approving_review_count = 1
            restrict_dismissals             = false
        }

        restrict_pushes {
            blocks_creations = false
            push_allowances  = []
        }
    }

  # module.github.module.genny.github_repository.this will be updated in-place
  # (imported from "genny")
    resource "github_repository" "this" {
        allow_auto_merge            = false
        allow_merge_commit          = false
        allow_rebase_merge          = false
        allow_squash_merge          = true
        allow_update_branch         = false
        archived                    = false
        auto_init                   = false
        default_branch              = "master"
        delete_branch_on_merge      = false
        description                 = "🧞\u200d♀️ Grants 3 wishes. As long as those wishes are to generate load 🧞\u200d♂️"
        etag                        = "W/\"1561743c78a99f870325f27e254ebca3701f6af56bc9df1ae604fb59e8693de4\""
        full_name                   = "mongodb/genny"
        git_clone_url               = "git://github.com/mongodb/genny.git"
        has_discussions             = false
        has_downloads               = true
        has_issues                  = true
        has_projects                = false
        has_wiki                    = false
        html_url                    = "https://github.com/mongodb/genny"
        http_clone_url              = "https://github.com/mongodb/genny.git"
        id                          = "genny"
        is_template                 = false
        merge_commit_message        = "PR_TITLE"
        merge_commit_title          = "MERGE_MESSAGE"
        name                        = "genny"
        node_id                     = "MDEwOlJlcG9zaXRvcnkxMjEyOTEwNDg="
        primary_language            = "C++"
        private                     = false
        repo_id                     = 121291048
        squash_merge_commit_message = "COMMIT_MESSAGES" 
        squash_merge_commit_title   = "COMMIT_OR_PR_TITLE"
        ssh_clone_url               = "git@github.com:mongodb/genny.git"
        svn_url                     = "https://github.com/mongodb/genny"
        topics                      = []
        visibility                  = "public"
        vulnerability_alerts        = true
        web_commit_signoff_required = false

        security_and_analysis {
            secret_scanning {
                status = "enabled"
            }
            secret_scanning_push_protection {
                status = "enabled"
            }
        }
    }
```

### Review Notes

@jawwadasghar I added you and @mongodb/performance as reviewers because you asked for this directly.

@johndaniels, @dalyd, @jimoleary I added you as people who frequently edit the non-workload parts of this repo to give you a chance to veto.

I am trying to keep the CODEOWNERS minimal and not very expansive

### CODE REVIEW

**Review by dalyd — COMMENTED** [review]
James mentioned including me so I could veto. I do not wish to veto this :) 
I would like it more expansive. 

Also, if we do this, could we make a similar update to privateworkloads? https://github.com/10gen/PrivateWorkloads/ I think product perf owns almost all of that except for yamllint and gitignore files.

**Review by johndaniels — APPROVED** [review]

**Review by jawwadasghar — APPROVED** [review]
LGTM

**Comment by thessem** [comment]
@dalyd I have added the generic catch-all, I'll merge this with just your approval.

**Review by dalyd — APPROVED** [review]

**Comment by thessem** [comment]
evergreen merge

**Pull request merged**
