### PR TITLE
PERF-2939 Exclude the lookup pushdown workloads from running on v4 branches

### PR DESCRIPTION
**Pull request by yun-soo**
Given that we onboarded LookupSBEPushdown.yml and LookupSBEPushdownINLMisc.yml to compare the SBE lookup perf to the classic lookup perf, It's not necessary to run two workloads on v4 branches.

It looks like that the Quiesce actor won't work on v4.0 branch, looking at this patch build. The patch in the run disabled Quiesce actor in lookup_sbe_pushdown workloads which is successful but lookup_sbe_pushdown_inlj_misc workload failed.
https://spruce.mongodb.com/version/625487fa1e2d1770ebbec3f9/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

Scheduled another patch build with this patch:
https://spruce.mongodb.com/version/6254975657e85a4a74752e74/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

### CODE REVIEW

**Comment by yun-soo** [comment]
@dalyd, is there any chance for you to be able to review this PR? If you're not available, I can ask someone else to review this.

**Comment by dalyd** [comment]
Sorry,  I'm ooo right now.

**Review by yzhang1991 — APPROVED** [review]

**Comment by yun-soo** [comment]
evergreen merge

**Comment by yun-soo** [comment]
evergreen merge

**Comment by yun-soo** [comment]
evergreen merge

**Comment by yun-soo** [comment]
evergreen merge

**Comment by yun-soo** [comment]
evergreen merge

**Comment by yun-soo** [comment]
evergreen merge

**Pull request merged**
