### PR TITLE
PERF-4973 Add TS benchmark for a complex reporting task

### PR DESCRIPTION
**Pull request by albymassari**
The plan for this report requires supporting OR, filters on dotted paths, supporting dateTrunc, removing a few makeObj to avoid working on result document, allowing an unwind on non-block data, supporting grouping on compound key

Edit: PR link: https://spruce.mongodb.com/task/sys_perf_linux_3_node_replSet_all_feature_flags.2022_11_time_series_telemetry_patch_457b601676c17188abea53cf8c5b2c055e086581_657abde161837d04a2184d31_23_12_14_08_34_27/tests?execution=0&sortBy=STATUS&sortDir=ASC

### CODE REVIEW

**Comment by fotiniAlvanaki** [comment]
I believe you need to submit a New Workload ticket. have you done it?
https://github.com/10gen/performance-tooling-docs/blob/a9d69625b9331bca3d4cbb1f4b47df324dfd3919/new_workloads.md#L1

**Comment by albymassari** [comment]
Yes, I compiled it today

**Review by fotiniAlvanaki — APPROVED** [review]
LGTM

**Review by miguelangelnieto — APPROVED** [review]

**Comment by albymassari** [comment]
evergreen merge

**Pull request merged**
