### PR TITLE
SERVER-81424 Use insertMany command for changestream source

### PR DESCRIPTION
**Pull request by yun-soo**
Hi @Aadeshp,

As we discussed on the Slack, made some changes to `Passthrough_ChangeStream.yml` file and also there's a typo like `multipler` (I think you meant `multiplier`) and so I changed them to `step`. And lastly, `&Url` definitions were squiggled on vscode yaml file viewer and hard to see. So, I fixed it. Will schedule a sys-perf patch build soon.

### CODE REVIEW

**Comment by Aadeshp** [comment]
amazing, thank you @yun-soo !

**Review by Aadeshp — APPROVED** [review]

**Comment by yun-soo** [comment]
Just got the perf result for `Passthrough.ChangeStreamSource.Stats.Throughtput` and it's 4424.76 which was 2532 before. Going to merge this.

**Comment by yun-soo** [comment]
evergreen merge

**Comment by yun-soo** [comment]
Sorry @Aadeshp, I was looking at the perf results for https://github.com/10gen/mongo-enterprise-modules/pull/1647.

The patch build for this changes is taking too long time: https://spruce.mongodb.com/version/6543bb420ae6063341d967de/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

I might screw up something. Let me wait for a little more.

**Comment by yun-soo** [comment]
I kept getting system failure error for these changes on Evergreen and I could not get this PR over the finish line. I'm closing this PR for now to save reviewer's time.

**Pull request closed without merging**
