### PR TITLE
PERF-5990 Remove ConnectionsBuildup, run QE workloads on 3-Shard FLE, and unschedule InsertRemove

### PR DESCRIPTION
**Pull request by alicedoherty**
**Jira Ticket:** [PERF-5990](https://jira.mongodb.org/browse/PERF-5990)/[BF-35328](https://jira.mongodb.org/browse/BF-35328)

### Whats Changed
This PR addresses a couple small bugs:
- Removes the ConnectionsBuildup workload file (accidentally, only the phase file was deleted in https://github.com/mongodb/genny/pull/1267)
- Changes AutoRun references from `shard-lite-fle` to `shard-lite` (see https://github.com/10gen/dsi/pull/2046)
- Unschedule InsertRemove, which was recently readded to fix the DSI merge queue (see https://github.com/mongodb/genny/pull/1271) 

### Patch Testing Results
- [Patch](https://spruce.mongodb.com/patch/6707fc344e5f7f0007c3089e/configure/tasks) (I didn't run anything, but confirmed connections_buildup and insert_remove no longer can be scheduled, and all the QE stuff is on the 3-shard FLE variant)

### CODE REVIEW

**Comment by alicedoherty** [comment]
Going to keep this in a draft state until it's decided what's happening with the recently deleted Genny workloads, see https://github.com/mongodb/genny/pull/1270. fyi @jawwadasghar

**Review by thessem — APPROVED** [review]
I am personally happy with this so long as it doesn't break DSI. We're working on making this harder to accidentally do

**Review by jimoleary — APPROVED** [review]
LGTM

**Comment by alicedoherty** [comment]
Running sanity DSI patch [here](https://spruce.mongodb.com/version/6708de82b36eed0007811e41/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) to make sure this won't break the commit queue/self-tests

**Pull request merged**
