### PR TITLE
PERF-5826: Update multiplanner workload definitions to exclude v7.3 for change of plan cache

### PR DESCRIPTION
**Pull request by mattsimply**

### CODE REVIEW

**Comment by mattsimply** [comment]
[patch](https://spruce.mongodb.com/version/66c7634f8d71390007860c9e/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

**Comment by mattsimply** [comment]
[Original patch from BF](https://spruce.mongodb.com/version/sys_perf_7.3_e14517e5e944dab4755a016e31b9b2f991327128_68d390e9851c6b36533ab3b362cc040c/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

[Repro patch (before changes)](https://spruce.mongodb.com/version/66c6597756abb7000776849b/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

**Comment by nzolnierzmdb** [comment]
@mattsimply do you have an updated perf patch?

**Comment by jimoleary** [comment]
This PR is marked as a draft, do you actually want a review?

**Comment by mattsimply** [comment]
[patch after fixing all relevant .yml files](https://spruce.mongodb.com/version/66c8866a17703d00076bbc1b/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

**Comment by mattsimply** [comment]
@jimoleary yes, thank you! now it is ready for review! I just wanted to make sure that the patch is green.

**Review by nzolnierzmdb — APPROVED** [review]

**Review by jimoleary — APPROVED** [review]
LGTM on these changes.

Did `$gt: v7.3` also work? Just wondering if we need to raise a ticket if it didn't work as expected.

**Comment by mattsimply** [comment]
In this [patch](https://spruce.mongodb.com/version/66c7634f8d71390007860c9e/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) the task generation failed. So then I checked whether ```$gt``` is used in any other .yml file, and couldn't find any other occurrence. So I changed to ```$gte``` and the patch seemed to pass. I couldn't find any relevant documentation on the syntax.

**Pull request merged**
