### PR TITLE
PERF-5545 Add scoreFusion workload

### PR DESCRIPTION
**Pull request by cswanson310**
### Whats Changed

Extending the workload to add a score fusion based pipeline.

### Patch Testing Results

https://spruce.mongodb.com/version/66ce3b4b6d5bcd0007f61029/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

### CODE REVIEW

**Comment by miguelangelnieto** [comment]
I think the conflicts need to be fixed before I start the review. I will follow the PR.

**Comment by cswanson310** [comment]
Sorry about that! Fixed up the branch but I had to force push to override the history.

**Comment by miguelangelnieto** [comment]
I have no issues with the code itself, but the patch test failed. I would like to have a successful patch test to see the results and the logs.

**Review by miguelangelnieto — CHANGES_REQUESTED** [review]
I have no issues with the code itself, but the patch test failed. I would like to have a successful patch test to see the results and the logs.

**Comment by cswanson310** [comment]
@miguelangelnieto that was a good thing to double check. I had accidentally duplicated a name of the metric, so it wasn't reporting it. I fixed that, but even my latest patch isn't reporting the metric I'd expect. Do you have any idea why that might be? I'm expecting to find "ScoreFusionUsingSigmoid" in [here](https://spruce.mongodb.com/task/sys_perf_perf_3_node_replSet.arm.aws.2023_11_non_search_hybrid_scoring_patch_637bd8fd8d949ff659b852f3a40631f599abf43d_66d7773097f10a0007e9e2ef_24_09_03_20_54_48/trend-charts?execution=0&sortBy=STATUS&sortDir=ASC), but I don't see it. 

Ah, actually I just figured it out - it looks like it's not part of the "default sys-perf metrics" context? Is there a problem there?

Anyway, here's the full patch: https://spruce.mongodb.com/version/66d7773097f10a0007e9e2ef/tasks?page=0&sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC&taskName=non_search

**Comment by miguelangelnieto** [comment]
> Ah, actually I just figured it out - it looks like it's not part of the "default sys-perf metrics" context? Is there a problem there?

The build baron team only triages those metrics that are part of the "default sys-perf metrics" context. This is not an issue with your workload, it just means that if you want changes to be triaged, we would need to add ScoreFusionUsingSigmoid to the default sys-perf metrics context. If this is what you want, please feel free to open a PERF ticket.

The patch test looks good. So I am going to give the LGTM.

**Review by miguelangelnieto — APPROVED** [review]

**Review by TedTuckman — APPROVED** [review]

**Pull request merged**
