### PR TITLE
PERF-3059 Remove cache warmup phases

### PR DESCRIPTION
**Pull request by yun-soo**
Companion PRs:
- https://github.com/10gen/dsi/pull/1063
- https://github.com/10gen/mongo/pull/6151

### CODE REVIEW

**Review by jimoleary — CHANGES_REQUESTED** [review]
It looks like you still need to update the workload description to change the phases / actors.

Do these changes have an effect on performance, i.e. do we need to let the barons know that this will cause a BF?

**Comment by yun-soo** [comment]
> It looks like you still need to update the workload description to change the phases / actors.

Thanks for review, Jim. Updated the description.
> 
> Do these changes have an effect on performance, i.e. do we need to let the barons know that this will cause a BF?

I think it would effect on perf to a certain degree but I asked the perf-build-baroning channel to ignore the perf suite until I'll say otherwise. Since then, I've never asked to monitor the perf suite. Is there any systematic way to mark a test suite as "should be ignored" state for perf build baroning other than asking the channel to do so? As of now, the feature is still under active development.

**Comment by jimoleary** [comment]
> ... but I asked the perf-build-baroning channel to ignore the perf suite until I'll say otherwise. 

Of course. At the moment, there is no better way to do this.

**Review by jimoleary — APPROVED** [review]

**Comment by yun-soo** [comment]
Abandoning this PR after talking with @YuhongZhang98.

**Pull request closed without merging**
