### PR TITLE
PERF-4371 Include non-standalone variants for query-stats specific tests

### PR DESCRIPTION
**Pull request by cswanson310**
@naafiyan realized this didn't work in his experiments for SERVER-78749.

**Patch testing results:**  
[🌲 link](https://spruce.mongodb.com/version/64b895e5a4cf4707d4987291/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

### CODE REVIEW

**Review by naama-bareket — APPROVED** [review]
lgtm with a green evergreen build!

**Comment by cswanson310** [comment]
Looks like the sharding variant didn't work, and it appears to be because our sharded dsi variant configures the query stats collection on the mongod instead of the mongos: https://github.com/10gen/dsi/blob/1df0818771c20d5b9f5978bb5465aecc69042af7/configurations/mongodb_setup/mongodb_setup.shard-query-stats.yml#L18 (that should be under mongos_config_file not mongod)

I'll file a separate ticket to fix that, but remove the sharded configurations for now.

**Comment by cswanson310** [comment]
evergreen merge

**Comment by cswanson310** [comment]
Filed https://jira.mongodb.org/browse/PERF-4443 for the sharding issue.

**Pull request merged**
