### PR TITLE
EVG-19833 Update TOOLCHAIN_BUILD_ID to avail ubuntu2204 toolchains and add mongod ubuntu2204 download link

### PR DESCRIPTION
**Pull request by lgfang**
****Jira Ticket:**** EVG-19833

****Whats Changed:****

Update TOOLCHAIN\_BUILD\_ID to one that builds the toolchain for ubuntu2204 amd64 and arm64.

****Patch testing results:****

The following genny cmake-test and resmoke-test succeeded on ubuntu2204 x86\_64:

```text
sudo mkdir -p /data/db
sudo chown ${whoami}:${whoami} /data/db
./run-genny clean
./run-genny create-new-actor HelloWorldActor
sed -i '/program_executable/s!:.*$!: ../../build/src/cast_core/cast_core_test!' ./src/resmokeconfig/genny_single_node_replset.yml
sed -i '/REQUIRE(count == 101)/s/101/100/' ./src/cast_core/test/HelloWorldActor_test.cpp
./run-genny install -d ubuntu2204
./run-genny cmake-test
./run-genny resmoke-test --suites ../../src/resmokeconfig/genny_single_node_replset.yml
```

### CODE REVIEW

**Review by thessem — APPROVED** [review]

**Comment by thessem** [comment]
I added @johndaniels as a reviewer to verify that that this won’t upset and genny latencies (it it does we should hold off on merging). Guessing it won’t though

**Comment by thessem** [comment]
> That said, I'm happy to wait for @johndaniels to confirm/approve.

I’m happy with that, removed him as a reviewer, hopefully I didn’t generate too many emails!

**Review by johndaniels — APPROVED** [review]
Yeah this really shouldn’t impact it.

**Comment by lgfang** [comment]
evergreen merge

**Pull request merged**
