### PR TITLE
TIG-2201 Added autorun section to Large Scale Model workload

### PR DESCRIPTION
**Pull request by ddanderson**

### CODE REVIEW

**Comment by ddanderson** [comment]
@rtimmons Can you review please?  Per our discussion this afternoon.

**Comment by ddanderson** [comment]
evergreen merge

**Comment by ddanderson** [comment]
@rtimmons, can you please merge?  I don't think `evergreen merge` works for me, it doesn't look like anything happened.

**Comment by rtimmons** [comment]
evergreen merge

**Pull request merged**
