### PR TITLE
DEVPROD-1999: Run Actor tests on as many topologies as possible 

### PR DESCRIPTION
**Pull request by PyGeek03**
**Jira Ticket:** [DEVPROD-1999](https://jira.mongodb.org/browse/DEVPROD-1999)

**Whats Changed:**  
Run Actor tests on as many topologies as possible.

Since [genny_standalone.yml was removed](https://github.com/mongodb/genny/pull/418/files#diff-3d7334da0f966176da042540b0d5f1f24cd6a657bda76d8d6b8c31457a84b06a) and hence the tag `[standalone]` disabled, some actor test cases have stopped running. For some actors, this resulted in a drift between an actor's new modifications and its test code, for example `CollectorScanner` actor. Such test code has been fixed in this PR.

However, I discovered 3 Actors that might have correctness bugs: StreamStatsReporter (for all topologies), MultiCollectionQuery (for `[three_node_replset]` and `[sharded]`), and DbCheckActor (for `[sharded]`). I disabled their tests for now, but I think these should be addressed in another ticket to ensure test results' integrity.

**Patch testing results:** 
Not necessary because all changes are in test code.

### CODE REVIEW

**Comment by PyGeek03** [comment]
Hi @Aadeshp, I just wanted to let you know regarding the possible correctness bug in StreamStatsReporter actor.

**Review by thessem — CHANGES_REQUESTED** [review]
I'm not sure I fully understand what this PR is doing. This is my lack of experience with the C++ testing suite here, not your description.

From the description it looks like the intention is to run the test cases for as many topologies as we can, but they must be manually written in as tags under `TEST_CASE_METHOD`. This seems like an inversion of the intended design of the tags, which (from what I understand) is an allow-list of topologies for each test, and might also function as bad documentation about the intention of each actor?

If this read is correct, wouldn't it be better to reverse the polarity of the tags and turn them into "topologies we don't test on" instead, with the goal of having each actor with an empty list, or a comment for each entry as to why it doesn't make sense to run the actor tests for that topology?

**Comment by PyGeek03** [comment]
@thessem I'm not sure if reverting is possible, but I'm sure that if we do that, it will be a giant change, because we'll have to edit every single existing test case, not just these test cases.

**Comment by Aadeshp** [comment]
> Hi @Aadeshp, I just wanted to let you know regarding the possible correctness bug in StreamStatsReporter actor.

hey @PyGeek03 , not sure if I follow, what correctness bugs exactly?

**Comment by thessem** [comment]
> @thessem I'm not sure if reverting is possible, but I'm sure that if we do that, it will be a giant change, because we'll have to edit every single existing test case, not just these test cases.

With the PR right now I don't understand why topologies have been added to `CollectionScannerGenerateCollectionNames` specifically, aside from it's in the set of tests that used to have `[standalone]` on them. I'm not sure I understand why adding all topologies to a specific list of tests is worth doing, if we're not adding them (and deny-listing) to all tests.

**Comment by PyGeek03** [comment]
From my understanding, unless otherwise specified, Genny workload authors are free to include any actors into a new workload that might be run on any topology. Therefore, not testing them on all topologies might lead to incorrect test data.

Simply reinstating the file genny_standalone.yml is not an option, since the PR that removed it also added [this comment](https://github.com/mongodb/genny/pull/418/files#diff-18df3e2ba4f534c8a4b8c1d123fb89bdeaa0229641993ac244e63ba3a106fc7cR167-R171):

```
  # It's not possible to do a standalone version due to
  # some tests' reliance on an apm callback that doesn't
  # work on standalone. (Specifically, since read concern
  # is irrelevant on a standalone, recent driver versions
  # simply omit it.)
```

Regarding the actors I mentioned above (unless the test itself has a bug under a topology, then the actor might have a bug):

- For `StreamStatsReporter`, this actor is used in workloads specified in [this DSI test_control YML](https://github.com/10gen/dsi/blob/b60fa0bda7a5ce33d63133feaee9a8a0b8351fdb/configurations/test_control/test_control.streams.2023-10.yml). These workloads are ran in [sys-perf](https://github.com/mongodb/mongo/blob/bc6c8d074d2d84c59c0f4d5556c5c6a4c6fa8161/etc/system_perf.yml#L2648-L2670), using single node replset variant configuration ([infrastructure_provisioning config](https://github.com/10gen/dsi/blob/b60fa0bda7a5ce33d63133feaee9a8a0b8351fdb/configurations/infrastructure_provisioning/infrastructure_provisioning.streams-single.intel.2023-10.yml#L15), [mongodb_setup config](https://github.com/10gen/dsi/blob/b60fa0bda7a5ce33d63133feaee9a8a0b8351fdb/configurations/mongodb_setup/mongodb_setup.streams-single.2023-10.yml#L2)). However, when [[single_node_replset] is enabled](https://spruce.mongodb.com/version/655c637da4cf4784c8773c1b/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) for StreamStatsReporter_test.cpp, the patch fails. Patches that enable [[three_node_replset]](https://spruce.mongodb.com/version/655445be9ccd4e9211e4fca6/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) and [[sharded]](https://spruce.mongodb.com/version/6554457c562343b0a9b7f8af/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) also fail.

- For `MultiCollectionQuery`, this actor is used in the workloads [BigUpdate10k](https://github.com/mongodb/genny/blob/1a338021b269a1d92d9dce2a4a7e2af5d2445a8e/src/workloads/scale/BigUpdate10k.yml#L115), [BigUpdate](https://github.com/mongodb/genny/blob/1a338021b269a1d92d9dce2a4a7e2af5d2445a8e/src/workloads/scale/BigUpdate.yml#L115), and [LargeScaleLongLived](https://github.com/mongodb/genny/blob/1a338021b269a1d92d9dce2a4a7e2af5d2445a8e/src/workloads/scale/LargeScaleLongLived.yml#L61). BigUpdate10k is configured to run under sys-perf's [Linux 3-Node ReplSet 2022-11 variant](https://github.com/mongodb/mongo/blob/bc6c8d074d2d84c59c0f4d5556c5c6a4c6fa8161/etc/system_perf.yml#L4148). BigUpdate's AutoRun section includes [three node replset variants](https://github.com/mongodb/genny/blob/1a338021b269a1d92d9dce2a4a7e2af5d2445a8e/src/workloads/scale/BigUpdate.yml#L132-L136). LargeScaleLongLived's AutoRun section includes both [three node replset and sharded variants](https://github.com/mongodb/genny/blob/1a338021b269a1d92d9dce2a4a7e2af5d2445a8e/src/workloads/scale/LargeScaleLongLived.yml#L93-L95). However, patches that enable [[three_node_replset]](https://spruce.mongodb.com/version/655c678ba4cf4784c87741b1/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) and [[sharded]](https://spruce.mongodb.com/version/6552ecd80305b9e2e2bc3130/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) for MultiCollectionQuery_test.cpp both fail.

- For `DbCheckActor`, this actor is used in the workload [dbcheck_40GB](https://github.com/mongodb/genny/blob/1a338021b269a1d92d9dce2a4a7e2af5d2445a8e/src/workloads/replication/dbcheck/dbcheck_40GB.yml#L57) which has its own [DSI test_control YML](https://github.com/10gen/dsi/blob/b60fa0bda7a5ce33d63133feaee9a8a0b8351fdb/configurations/test_control/test_control.dbcheck.yml#L12). sys-perf runs this workload under the variant [Linux 3-Node ReplSet (all feature flags) 2022-11](https://github.com/mongodb/mongo/blob/bc6c8d074d2d84c59c0f4d5556c5c6a4c6fa8161/etc/system_perf.yml#L4558). DbCheckActor_test.cpp passes for both [three_node_replset] and [single_node_replset], so currently there's no risk of incorrect test data. However, [it fails when [sharded] is enabled](https://spruce.mongodb.com/task/genny_amazon2_arm64_t_integration_test_sharded_patch_28d4e7b8e7ca2171d260b17e92b45d78542b2f8d_6552eef0e3c3311e8dfd521a_23_11_14_03_52_29/logs?execution=0&sortBy=STATUS&sortDir=ASC), so there is a risk of incorrect test data if this actor is used under a sharded variant.

**Review by thessem — APPROVED** [review]

**Comment by PyGeek03** [comment]
evergreen merge

**Pull request merged**
