### PR TITLE
PERF-2927 Enable the SBE lookup-related Genny workloads

### PR DESCRIPTION
**Pull request by yun-soo**
Given that all lookup algorithms are working end-to-end and produce correct results, this PR enables the SBE lookup-related workloads on Evergreen sys-perf project.

### CODE REVIEW

**Review by dalyd — APPROVED** [review]

**Comment by dalyd** [comment]
Could you do a patch build of this before merging, just to make sure the test still runs and we haven't missed something stupid?

**Comment by yun-soo** [comment]
Thanks for review, @dalyd! I've already run a patch build here:
https://spruce.mongodb.com/version/624e45b23627e03938be5488/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

Mainly interested workloads are `lookup_sbe_pushdown` and `lookup_sbe_pushdown_inlj_misc` on both non-feature-flag build variant and all-feature-flags build variant. Would this be enough for you?

I don't hear from you in a few hours, I'll merge this PR as is.

**Comment by dalyd** [comment]
Yeah, that sounds fine.


*{* name     : "David Daly",
  title    : "Staff Engineer -- Server Product Performance",
  location : "New York, NY",
  twitter  : ***@***.*** <https://twitter.com/daviddaly44>",
  website  : "daviddaly.me" *}*

**Comment by yun-soo** [comment]
Thanks again! Really appreciate it.

**Comment by yun-soo** [comment]
evergreen merge

**Pull request merged**
