### PR TITLE
PERF-2075 new mass deletion workload

### PR DESCRIPTION
**Pull request by ghartnett**

### CODE REVIEW

**Comment by ghartnett** [comment]
I have already tested this many many times
https://spruce.mongodb.com/version/605e4a7bd1fe070c0e47885e/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC

**Review by rtimmons — APPROVED** [review]
LGTM. FWIW STM doesn't need to be on reviews for workload yamls not owned by STM. Happy to lend a set of eyes but we don't need to block your progress.

**Comment by ghartnett** [comment]
Thanks Ryan

**Comment by ghartnett** [comment]
evergreen merge

**Pull request merged**
