### PR TITLE
EVG-19923: Update Genny dependencies flagged by Dependabot

### PR DESCRIPTION
**Pull request by PyGeek03**
**Jira Ticket:** [EVG-19923](https://jira.mongodb.org/browse/EVG-19923)

**Whats Changed:**  
Update Genny dependencies flagged by Dependabot [here](https://github.com/mongodb/genny/security/dependabot).

**Patch testing results:**
- [sys-perf](https://spruce.mongodb.com/version/649942a70ae606c012941377/tasks?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC)

**Related PRs:**   
https://github.com/10gen/dsi/pull/1318

### CODE REVIEW

**Review by thessem — APPROVED** [review]
Thank you for this. I don't see any reason to hold off merging it, this change should not affect performance results and if the sys-perf tests pass I am happy.

Noting specifically that PyYAML changed case in the diff, but I believe the python tooling is case insensitive.

**Review by thessem — APPROVED** [review]
Happy with this. I would like to delay merging this in until we can get a good way of proving that Genny changes aren't going to create changepoints, but unless a scope on that is forthcoming within a few days I am happy to merge this in regardless. The changes in python look very safe and python isn't in the critical performance path.

**Comment by PyGeek03** [comment]
I've ran a [sys-perf patch](https://spruce.mongodb.com/version/64a6957e562343effb1b1303/changes?sorts=STATUS%3AASC%3BBASE_STATUS%3ADESC) with changes from both this PR and https://github.com/10gen/dsi/pull/1318, then check with [Perf Analyzer](https://performance-analyzer.server-tig.prod.corp.mongodb.com/perf-analyzer-viz/?comparison_id=4ffa171f-7fbd-4a1a-99b1-e7d7232e0254&percent_filter=0%7C%7C100&z_filter=0%7C%7C10) if there's any performance changes. There seems to be no changes, so I'll go ahead and merge both PRs.

**Comment by PyGeek03** [comment]
evergreen merge

**Pull request merged**
