### PR TITLE
PERF-3767 Remove excess MultiDelete workloads

### PR DESCRIPTION
**Pull request by haleyConnelly**

### CODE REVIEW

**Review by haleyConnelly — COMMENTED** [review]
The only remaining MultiDelete files are as follows:

src/phases/execution/MixedMultiDeletes.yml
src/phases/execution/config/MultiDeletes/Default.yml
src/phases/execution/config/MultiDeletes/WithSecondaryIndexes.yml

src/workloads/execution/MixedMultiDeletesDocByDoc.yml
src/workloads/execution/MixedMultiDeletesDocByDocWithSecondaryIndexes.yml
src/workloads/execution/MixedMultiDeletesBatched.yml
src/workloads/execution/MixedMultiDeletesBatchedWithSecondaryIndexes.yml


The phases/execution/config and phases/execution/config/MultiDeletes folder is strictly for the 2 files (Default and WithSecondaryIndexes). We could rename them and put them in them main phases/execution folder. However, I think it is fine as is. 

Genny has some limitations with parsing dicts versus strings that made it tough to combine the files / rework them to live in the main phases/*/MixedMultiDeletes.yml file while keeping the flexibility to choose with/without secondary indexes from a workload file.

**Review by ykangpark — COMMENTED** [review]
@haleyConnelly just took another look at PERF-3494 description and realized that it was suggested we remove these tests from running in the all feature flag variants. The new tests are still running in all feature flag variant, was that considered?

**Comment by haleyConnelly** [comment]
@ykangpark Thanks for catching that, the new files have been updated

**Review by ykangpark — APPROVED** [review]
LGTM! Thanks!

**Pull request merged**
