### PR TITLE
DEVPROD-1896: Genny commit queue should dry-run all workloads exactly once, for each variant

### PR DESCRIPTION
**Pull request by PyGeek03**
**Jira Ticket:** [DEVPROD-1896](https://jira.mongodb.org/browse/DEVPROD-1896)

**Whats Changed:**  
1) `t_test_create_new_actor_script` only dry-runs the workload YAML file it generated.
2) For Amazon Linux 2 arm64 & Amazon Linux 2 x64 variants: dry-run all workloads only once (in `t_compile_and_dry_run_asan`). 
3) For other variants that only dry-run without asan: rename the task to `t_compile_and_dry_run`, to prevent confusion for Genny repo's contributors.

Compared with previous Genny commit queue patches:
- "Time taken" has decreased: previously at least 8h, now about 5h 50m. So a saving of **minimum 2h per patch**.
- "Makespan" stays the same. Which is expected, because makespan is dominated by `t_compile_and_dry_run_asan` as can be seen [here](https://spruce.mongodb.com/version/6542ea202fbabe952e7db761/task-duration?duration=DESC).

### CODE REVIEW

**Review by johndaniels — APPROVED** [review]

**Comment by johndaniels** [comment]
I'm surprised dry_run takes that long.

**Review by thessem — APPROVED** [review]
Thank you for the great PR write up. Like John I'm surprised we were wasting that much time. I wonder how much compute $ this translates to per-genny patch

**Comment by PyGeek03** [comment]
evergreen merge

**Comment by PyGeek03** [comment]
evergreen merge

**Pull request merged**
