### PR TITLE
PERF-5712: Implement a performance test for long constant array in $filter of $project

### PR DESCRIPTION
**Pull request by wqian94**
**Jira Ticket:** [PERF-5712](https://jira.mongodb.org/browse/PERF-5712)

### Whats Changed

Add a new test case to the `ProjectParse` test suite for `$project`s with `$filters` containing large predicates.

### Patch Testing Results

[Patch](https://spruce.mongodb.com/version/66a29eda1b15c70007fe8965).

### CODE REVIEW

**Review by jimoleary — COMMENTED** [review]
The change itselfs looks fairly straightforward.

There is a big difference in average latency between the different variants (600ms to 360ms), is this expected and do we have any idea how noisy the results are?

Can you run a multipatch test and get the Coffecient of variation for the important metrics?

**Comment by wqian94** [comment]
[Multipatch](https://performance-analyzer.server-tig.prod.corp.mongodb.com/perf-analyzer-viz/?comparison_id=a35f14a2-7a3d-4167-8f29-a47250c9aa92).

**Comment by jimoleary** [comment]
The values are very large but the [CVs](https://performance-analyzer.server-tig.prod.corp.mongodb.com/perf-analyzer-viz/?comparison_id=a35f14a2-7a3d-4167-8f29-a47250c9aa92&selected_tab=data-table&task_filter=project_parse&test_filter=ProjectQueries.ProjectWithFilterParseLarge&percent_filter=0%7C%7C100&z_filter=0%7C%7C10) are all very good!

**Review by jimoleary — APPROVED** [review]
LGTM

**Comment by wqian94** [comment]
Looks like [CoV](https://performance-analyzer.server-tig.prod.corp.mongodb.com/perf-analyzer-viz/?comparison_id=a35f14a2-7a3d-4167-8f29-a47250c9aa92&selected_tab=data-table&test_filter=ProjectQueries.ProjectWithFilterParseLarge&percent_filter=0%7C%7C100&z_filter=0%7C%7C10) is around 1-2% for tput, 1-2% for Latency 50, and 1.5-3.5% for Latency 95. That seems stable-ish to me, even if less than ideal.

**Pull request merged**
