### PR TITLE
TIG-2714 Move src/python into src/lamplib

### PR DESCRIPTION
**Pull request by rtimmons**
Reverts #404 which reverted #399. No changes since what was previously reviewed. It had to be reverted because the `src/python` path is hard-coded in DSI. A future change will fix that.
Patch: https://spruce.mongodb.com/version/5ff4dad17742ae413c05addb/tasks
Related change to DSI coming in hot.

### CODE REVIEW

**Comment by richardsamuels** [comment]
Mind if we merge #405 before this one? (it's just removing stall things from the README in src/python)

**Comment by rtimmons** [comment]
No problem, @richardsamuels. I won't put this for official review until the PB comes back clean.

**Comment by richardsamuels** [comment]
Is there a companion PR for dsi, which updates configurations/workload_setup/workload_setup.common.yml:88?
`88:        cd ./src/genny/src/python || exit 1`

**Comment by rtimmons** [comment]
@richardsamuels yes, that's https://github.com/10gen/dsi/pull/791

**Review by richardsamuels — APPROVED** [review]

**Pull request merged**
