### PR TITLE
TIG-2744 Fix GlobalRate in Large-Scale workloads

### PR DESCRIPTION
**Pull request by vincivans**
TIG-2744 move Globalrate of LargeScaleModel, LargeScaleLongLived, and LongLivedReader to each phases

### CODE REVIEW

**Review by rtimmons — APPROVED** [review]
Please send an FYI to the authors of the workload.

**Comment by vincivans** [comment]
> Please send an FYI to the authors of the workload.

Send through the JIRA ticket or just github?

**Comment by rtimmons** [comment]
Just `@` them here as an FYI

**Comment by rtimmons** [comment]
Please also put a more descriptive title for the PR so it's more obvious when looking through the project history what the actual change was. Usually we do `$TICKET $TICKET_DESCRIPTION` so this would be something like

> TIG-2744 Fix GlobalRate in Large-Scale workloads

If you use the ticket number as a prefix the github/jira integration will automatically associate the PR with the ticket which is handy for doing code forensics in the future.

**Comment by vincivans** [comment]
FYI @dalyd @aggrand @luke-pearson @ddanderson

**Review by ddanderson — APPROVED** [review]
LGTM.

**Review by luke-pearson — APPROVED** [review]
LGTM.

**Review by dalyd — APPROVED** [review]

**Comment by vincivans** [comment]
evergreen merge

**Comment by vincivans** [comment]
evergreen merge

**Comment by vincivans** [comment]
evergreen merge

**Comment by vincivans** [comment]
evergreen merge

**Comment by vincivans** [comment]
evergreen merge

**Comment by vincivans** [comment]
evergreen merge

**Comment by vrachev** [comment]
Looks like this is running into https://jira.mongodb.org/browse/TIG-2943 (at least the last merge attempt). Should we just manually merge this and have someone look at TIG-2943 for BF Thursday? @rtimmons @guoyr

**Comment by vincivans** [comment]
evergreen merge

**Comment by vincivans** [comment]
evergreen merge

**Pull request merged**
