### PR TITLE
DEVPROD-2072: Mark more flaky Genny C++ tests on MacOS arm64

### PR DESCRIPTION
**Pull request by PyGeek03**
**Jira Ticket:** [DEVPROD-2072](https://jira.mongodb.org/browse/DEVPROD-2072)

**Whats Changed:**  
Add 2 more test cases to be ignored on MacOS arm64, as they are flaky.

I also modified currently ignored tests to use a single common label: `IgnoredOnMacOs`

**Patch testing results:**
Not needed as this change only concerns test code.

### CODE REVIEW

**Comment by PyGeek03** [comment]
These flaky tests failed recently in the Genny commit queue:

https://spruce.mongodb.com/task/genny_macos_1100_arm64_t_cmake_test_ignore_flaky_patch_bb28d64f781ab7302e2a8ba62d498443d21be784_64f739410305b983ce751687_23_09_05_14_21_02?execution=0&sortBy=STATUS&sortDir=ASC

**Review by thessem — CHANGES_REQUESTED** [review]
I would like to see a comment above each of these stating "MacOS does not have reliably accurate sleeps" or something similar. Otherwise I'm happy!

**Review by thessem — APPROVED** [review]
As promised, I am happy

**Comment by PyGeek03** [comment]
evergreen merge

**Pull request merged**
