### PR TITLE
TIG-2805 allow specifying ignoreError at the phase level

### PR DESCRIPTION
**Pull request by guoyr**
Followup to #393 

This works around the C++ driver issue.

green patch: https://evergreen.mongodb.com/build/sys_perf_linux_3_node_replSet_maintenance_events_patch_e36da1b27ef763f4d7367ddf0f2f97259c0deac3_5fd21592d1fe071a9dcae722_20_12_10_12_50_50

### CODE REVIEW

**Review by rtimmons — APPROVED** [review]
Plz update the crud actor docs yaml. Ideally we'd add a test-case but that may be hard to rig up. If adding tests for this isn't really feasible (ugh c++), please add a comment above these lines indicating that this logic isn't tested--alert somebody to potential dragons if they change this.

**Review by dalyd — APPROVED** [review]
Yeah -- more context on the ticket or in comments in the code would be appreciated. Change LGTM.

**Comment by guoyr** [comment]
Thanks for the feedback. I added a doc comment. The changes here and in #393 will be reverted once https://jira.mongodb.org/browse/SERVER-53431 lands; it's currently scheduled for the upcoming Repl sprint.

I don't think there's a more permanent need for recording failed commands as mongo makes more and more errors transparent to the end user.

**Comment by guoyr** [comment]
evergreen merge

**Pull request merged**
